### ISSUE TITLE
Fail to run on first start, missing jobs.json

### ISSUE THREAD

**Issue by MartinRosenberg** [alexlee-dev/job-app-viewer#24]
On first run, the app fails to start with an `UnhandledPromiseRejection` telling me that `./jobs.json` doesn't exist.

#### Reproduction

0. `git clone`
1. `npm install`
2. `npm run build`
3. `npm start`

#### Expected

The app starts

#### Actual

```
╰─ npm start

> applican@0.1.1 start /Users/Martin/Workspace/applican
> node lib/index.js

(node:29284) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/Martin/Workspace/applican/jobs.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MartinRosenberg** [comment]
Adding a `jobs.json` file containing an empty object prints the title, then fails with `Cannot read property 'forEach' of undefined`:

```
╰─ npm start

> applican@0.1.1 start /Users/Martin/Workspace/applican
> node lib/index.js
                      ╭──────────────────────────────────────────────────────────────────────────────────╮
                      │        __      __       ___                ___            __  _                  │
                      │       / /___  / /_     /   |  ____  ____  / (_)________ _/ /_(_)___  ____  _____ │
                      │  __  / / __ \/ __ \   / /| | / __ \/ __ \/ / / ___/ __ `/ __/ / __ \/ __ \/ ___/ │
                      │ / /_/ / /_/ / /_/ /  / ___ |/ /_/ / /_/ / / / /__/ /_/ / /_/ / /_/ / / / (__  )  │
                      │ \____/\____/_.___/  /_/  |_/ .___/ .___/_/_/\___/\__,_/\__/_/\____/_/ /_/____/   │
                      │                           /_/   /_/                                              │
                      ╰──────────────────────────────────────────────────────────────────────────────────╯
(node:29399) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at /Users/Martin/Workspace/applican/lib/util.js:80:18
    at new Promise (<anonymous>)
    at Object.exports.createTable (/Users/Martin/Workspace/applican/lib/util.js:75:12)
    at /Users/Martin/Workspace/applican/lib/util.js:108:50
    at step (/Users/Martin/Workspace/applican/lib/util.js:33:23)
    at Object.next (/Users/Martin/Workspace/applican/lib/util.js:14:53)
    at /Users/Martin/Workspace/applican/lib/util.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Martin/Workspace/applican/lib/util.js:4:12)
    at /Users/Martin/Workspace/applican/lib/util.js:102:60
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29399) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29399) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by actuallyReallyAlex** [comment]
I forgot that I had an uncommitted template file named jobs.json on my local machine. I'll fix this today. Standby for fix.

Thanks @MartinRosenberg 👍

**Comment by actuallyReallyAlex** [comment]
Hey @MartinRosenberg, please try the following steps:

1. Either just start over by re-cloning / re-forking this repo in a new directory OR copy just the jobs.json that exists in this repo now.
2. `npm install`
3. `npm run build`
4. `npm start`

This should get you to the main screen of Applican now.

Please let me know if you have any trouble. I'm closing this issue for now, but can reopen it if it's not working for you.

Thanks again!
